volumes:
  prometheus_data: {}
  loki_data: {}
  tempo_data: {}
  grafana_data: {}
 
services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.126.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./containers-data/otel-collector/config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      - loki
      - tempo
      - jaeger

  # Prometheus
  prometheus:
    image: prom/prometheus:v3.4.0
    volumes:
      - ./containers-data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - otel-collector

  # Loki
  loki:
    image: grafana/loki:3.5.0
    volumes:
      - ./containers-data/loki/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml


  init-tempo:
    image: grafana/tempo:2.7.2
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  # Tempo
  tempo:
    image: grafana/tempo:2.7.2
    volumes:
      - ./containers-data/tempo/tempo.yml:/etc/tempo.yaml
      - ./containers-data/tempo/data:/var/tempo
      - tempo_data:/tmp/tempo
    command: -config.file=/etc/tempo.yaml
    ports:
      - 3200:3200   # Tempo
    depends_on:
      - init-tempo
      - memcached 

  memcached:
    image: memcached:1.6.29
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Number of threads to use    

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.69.0
    ports:
      # - 4317:4317 #otlp grpc
      - "16686:16686" # UI
      - "14268:14268" # Collector API
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - ./containers-data/jaeger:/badger

  # Grafana
  grafana:
    image: grafana/grafana:12.0.0
    volumes:
      - grafana_data:/var/lib/grafana
      - ./containers-data/grafana/provisioning:/etc/grafana/provisioning
      - ./containers-data/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch tempoBackendSearch
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - loki
      - tempo
      - jaeger