apiVersion: 1

datasources:
  - uid: prometheus_ds
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - uid: loki_ds
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - uid: tempo_ds
    name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200

  - uid: jaeger_ds
    name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
