receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: EnvNameTest

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    # namespace: app
  debug:
    verbosity: detailed  # можно detailed, normal, basic
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  # sentry:
  #   dsn: https://<aaa>@<bbb>.ingest.de.sentry.io/<ccc>
  #   environment: prod
  #   insecure_skip_verify: true
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, otlp/tempo, debug]
    logs:
      receivers: [otlp]
      processors: [resource]
      exporters: [loki, debug]