{
 "title": "EShop Demo",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Общее количество попыток купить товары",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(try_orders_count_total{exported_job=\"EShop.OrderService\"})",
     "legendFormat": "Количество попыток"
    }
   ]
  },
  {
   "title": "Общее количество купленных товаров",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(success_orders_count_total{exported_job=\"EShop.OrderService\"})",
     "legendFormat": "Куплено товаров"
    }
   ]
  },
  {
   "title": "Логи",
   "type": "logs",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{EnvNameTest=\"EShop\"} \r\n| json \r\n| traceid = \"7f8c2bb2688261d73e1347cf5901d1b6\"\r\n| line_format \"{{.resources_service_name}}\\n **MSG:** {{.body}}\\n{{if .attributes_RequestPath}}**Path:** `{{.attributes_RequestPath}}`{{end}}\\n{{if .attributes_EndpointName}}**Endpoint:** `{{.attributes_EndpointName}}`{{end}}\\n---\""
    }
   ]
  },
  {
   "title": "Трассировка",
   "type": "traces",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 15 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "7f8c2bb2688261d73e1347cf5901d1b6",
     "tableType": "traces"
    }
   ]
  }
 ]
}